server:
  port: 8001
spring:
  application:
    name: train-ai
  profiles:
    active: dev
  security:
    user:
      name: root
      password: root


encrypt:
  salt: Qmj9YOYrRc86ub1Z

jwt:
  expiration: 5184000   #一个小时有效
  secret: 6rQhjE6d7nK27vkB5AteQ7ZWUa77E0g8HYcOe1FbL7lmDVSYdRiMM9VtriiLKig4
  issuer: com.superchakra


aliyun:
  access-key-id:
  access-key-secret:
